title: Linwei Sang
email: sanglinwei21@163.com
keyword: Electrical engineering
url: https://sanglinwei.github.io/
description: "Lin Sang's blog"
google_analytics: 
show_downloads: false

# sidebar: true
# sidebar-about-description: "请大家多多指教"
avatar: './images/sanglinwei.png'
round-avatar: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
      readtime: false # add estimated reading time on all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

theme: jekyll-theme-minimal

gems:
  - jekyll-mentions


