title: Linwei Sang
email: sanglinwei21@163.com
keyword: Electrical engineering
url: https://sanglinwei.github.io/
description: "Lin Sang's blog"
google_analytics: 
show_downloads: false

# sidebar: true
# sidebar-about-description: "请大家多多指教"
avatar: '/images/sanglinwei.png'

theme: jekyll-theme-minimal

gems:
  - jekyll-mentions


